language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
# command to run tests
script:
  - make
  - pytest --cov=src tests
after_success:
  - codecov -t 376fbdd4-aa15-48a7-b0ad-add2ee3eaba4